#!/bin/bash
#rm /home/pi/AwesomePhotobooth/TempPhotoBooth/*
mogrify -resize 968x648 /home/pi/AwesomePhotobooth/TempPhotoBooth/*.jpg
montage /home/pi/AwesomePhotobooth/TempPhotoBooth/*.jpg -tile 2x2 -geometry +10+10 /home/pi/AwesomePhotobooth/TempMontage/temp_montage2.jpg

suffix=$(date +%H%M%S)
cp /home/pi/AwesomePhotobooth/TempMontage/temp_montage2.jpg /home/pi/AwesomePhotobooth/PB_archive_Assembly/PB_${suffix}.jpg

rm /home/pi/AwesomePhotobooth/TempPhotoBooth/*.jpg

#rm /home/pi/photobooth_images/*.jpg

